#!/usr/bin/bash env

#sets up a new server and adds a header 'X-Served-By'
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
Server="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}"
sudo sed -i "29i $Server" /etc/nginx/sites-available/default
header="\\\tadd_header X-Served-By $HOSTNAME;"
sudo sed -i "79i $header" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
