#!/usr/bin/bash env
#sets up a new server and adds a header 'X-Served-By'
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
Service="\\\tlocation /redirect_me{\n\treturn 301 https://www.google.com/search?q=berserk%20manga&tbm=isch&rlz;\n\t}"
sudo sed -i "26i $Service" /etc/nginx/sites-available/default
Server="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}"
sudo sed -i "29i $Server" /etc/nginx/sites-available/default
header="\\\tadd_header X-Served-By $HOSTNAME;"
sudo sed -i "79i $header" /etc/nginx/sites-available/default
service nginx start
