#!/usr/bin/env bash
# Installs and sets up haproxy

apt-get -y update
apt-get -y upgrade
apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo chmod 666 /etc/haproxy/haproxy.cfg
sudo echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 45363-web-01 3.237.30.57:80 check
   server 45363-web-02 3.89.160.202:80  check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
