#!/usr/bin/env bash
# backups data from mysql db using the mysqldump comand
and then compresses it into a tar.tgz file
mysqldump --all-databases -u root --password="$1" > backup.sql
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"
tar -czvf "$file_name" backup.sql
