#!/usr/bin/env bash
#a fix for the nginx webserver running on the ubuntu container which doesn't listen for conections on port 80
sudo sed -i "21 '\\\tlisten 80 default_server;\n\tlisten [::]:80 default_server ipv6only=on;'" /etc/nginx/sites-available/default
sudo service nginx restart
pkill nginx
