#!/usr/bin/env bash
#prints 'Best School' unless on the 9th iterartion then print 'Hi afterwards
i=1

while [ $i -le 10 ]
do
	if [ $i -ne 9 ]
	then
		echo "Best School"
	else
		echo "Best School"
		echo "Hi"
	fi
	i=$(( i+1 ))
done
