#!/usr/bin/env bash
#prints badluck on 4 and good luck on 8th iteration
#otherwise prints Best School

i=1
while [ $i -lt 11 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(( i+1 ))
done
