#!/usr/bin/env bash
: '
prints the numbers from 1 to 20 but prints
bad luck from china, japan, italy on the
4th, 9th and 17th iteration respectively
'
i=1
while [ $i -le 20 ]
do
	case $i in
		4 )
		echo "bad luck from China"
		;;
		9 )
		echo "bad luck from Japan"
		;;
		17 )
		echo "bad luck from Italy"
		;;
		* )
		echo "$i"
		;;
	esac
	i=$(( i+1 ))
done
