#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
# except for TCP ports ssh, https and http.

sudo apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow ssh
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
